spring:
  datasource:
    url: jdbc:mysql://gz-cdb-rtzggr55.sql.tencentcdb.com:56814/newsmanagement
    username: user
    password: 789456123@qqcom
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

jhlyh:
  app:
    jwtCookieName: jhlyh
    jwtSecret: jhlyhKey
    jwtExpirationMs: 60000