spring:
  datasource:
    url: jdbc:mysql://114.132.251.197:3306/	newsmanagement
    username: newsmanagement
    password: dcBYr6tYbPkCyM5Z
  jpa:
    hibernate:
      ddl-auto: update
#  jpa:
#    generate-ddl: true



