spring:
#mysql
  datasource:
    url: jdbc:mysql://gz-cynosdbmysql-grp-0bw9tbgz.sql.tencentcdb.com:20771/news
    username: jhlyh
    password: 020202jhl@qq.com
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
#redis
  redis:
    database: 0
    host:  114.132.251.197
    port: 6379
    password: 789456123@qq.com
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-wait: -1ms
    connect-timeout: 30000ms
  data:
    redis:
      repositories:
        enabled: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#jwt
jhlyh:
  app:
    jwtCookieName: jhlyh
    jwtSecret: jhlyhKey
    jwtExpirationMs: 60000


